name: Prepare EKS config

description: Install kubectl, configure kubeconfig, create namespace, apply secrets, and validate inputs.

inputs:
  kubectl_version:
    description: kubectl version to install
    required: false
    default: v1.29.0
  demo_mode:
    description: If true, deploys HTTP-only ingress and prints ALB DNS (no Route53/ACM)
    required: true
  public_domain:
    description: Public domain for HTTPS ingress (required when demo_mode=false)
    required: false
  alb_acm_arn:
    description: ACM certificate ARN for HTTPS ingress (required when demo_mode=false)
    required: false

runs:
  using: composite
  steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: ${{ inputs.kubectl_version }}

    - name: Configure kubeconfig
      shell: bash
      run: |
        set -euo pipefail
        aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region "${EKS_REGION}" --kubeconfig .kubeconfig
        echo "KUBECONFIG=${GITHUB_WORKSPACE}/.kubeconfig" >> "$GITHUB_ENV"

    - name: Ensure namespace exists
      shell: bash
      run: |
        set -euo pipefail
        kubectl get namespace chatbot >/dev/null 2>&1 || kubectl create namespace chatbot

    - name: Apply DB/OpenAI secrets
      shell: bash
      run: |
        set -euo pipefail
        chmod +x ci/apply_db_secret.sh
        ./ci/apply_db_secret.sh

    - name: Validate inputs
      shell: bash
      run: |
        set -euo pipefail
        if [[ "${{ inputs.demo_mode }}" != "true" ]]; then
          if [[ -z "${{ inputs.public_domain }}" || -z "${{ inputs.alb_acm_arn }}" ]]; then
            echo "ERROR: demo_mode=false requires workflow inputs 'public_domain' and 'alb_acm_arn'." >&2
            exit 1
          fi
        fi
